name: deploy-non-prd
on:
  push:
    branches:
      - dev
      - main
jobs:
  code-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }}

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: create env file
      #   run: |
      #     touch .env
      #     echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      #     echo API_PORT=${{ secrets.API_PORT }} >> .env
      #     echo TOKEN=${{ secrets.TOKEN }} >> .env
      #     echo ORIGIN=${{ secrets.ORIGIN }} >> .env
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/lakkanan/backend:${{ env.ENV_NAME }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/lakkanan/backend:${{ env.ENV_NAME }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always() 
        with:
          sarif_file: 'trivy-results.sarif'

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
        
      # - name: deploy with Execute SSH commmands on remote server
      #   uses: JimCronqvist/action-ssh@0.1.1
      #   with:
      #     hosts: ${{ secrets.SSH_HOST }}
      #     privateKey: ${{ secrets.PRIVATE_KEY }}
      #     command: |
      #       docker pull ghcr.io/lakkanan/backend:${{ env.ENV_NAME }}
      #       docker rmi $(docker images | grep "<none>" | awk '{print $3}')
      #       docker-compose -f ~/docker-compose/app-compose.yml down
      #       docker-compose -f ~/docker-compose/app-compose.yml up -d
  test:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV

      # - name: OWASP ZAP Baseline Scan
      #   uses: zaproxy/action-baseline@v0.4.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     target: 'https://api.blackcarrack.tech'